const Map<String, String> appStringsEn = {
  'appName': 'WellnessDeck',
  'appTagline': 'Your offline lifestyle dashboard. No diagnosis. Just insight.',
  'loading': 'Loading…',
  'shop': 'Shop',
  'settings': 'Settings',
  'navToday': 'Today',
  'navBuild': 'Build',
  'navPatterns': 'Patterns',
  'navWorkspace': 'Build',
  'navCockpit': 'Patterns',
  'navSettings': 'Menu',
  'navShop': 'Shop',
  'navMore': 'Menu',
  'badgeOffline': '100% OFFLINE',
  'badgeNoConnect': 'NO CONNECTIONS',
  'hydration': 'Hydration',
  'cups': 'cups',
  'meals': 'Meals',
  'done': 'done',
  'movement': 'Movement',
  'min': 'min',
  'sleep': 'Sleep',
  'todaySubtitle': 'Your deck for balance',
  'buildTitle': 'Build My Day',
  'buildSubtitle': 'Design a day that supports you',
  'patternSubtitle': 'Understand your rhythms',
  'sleepGoalShort': 'Goal 7-9 h',
  'steps': 'steps',
  'breath478title': '4-7-8',
  'breathMin': '2 min',
  'breathMinPlus': '4 min',
  'intentionPlaceholder': 'I choose focus and kindness',
  'moodPlaceholder': 'Grateful, calm',
  'patternObservation': 'Pattern Observation',
  'observationOnly': 'Observation only. Not a rule.',
  'days7': '7 Days',
  'days30': '30 Days',
  'days90': '90 Days',
  'activity': 'Activity',
  'journaling': 'Journaling',
  'experimentSample': 'Morning light + hydration',
  'reflectHint': 'What went well? What can I adjust?',
  'eveningLine': '8:30 PM Wind down & reflect',
  'mood': 'Mood',
  'moodHint': 'Tap to log a word',
  'breathing': 'Breathing',
  'breath478': '4-7-8 · 2 min',
  'routines': 'Routines',
  'morningFlow': 'Morning Flow',
  'stepsLeft': 'steps left',
  'sleepGoal': 'Goal 7–9 h · typed in',
  'intention': 'Daily Intention',
  'intentionHint': 'A sentence for today',
  'tapToLog': 'Tap to log',
  'notMedical': 'Not a diagnosis. No HealthKit, wearables, or medical claims. Insight only.',
  'workoutPlan': 'Workout Plan',
  'mealNotes': 'Meal Notes',
  'addANote': 'Add a note',
  'habitStack': 'Habit Stack',
  'screenBreak': 'Screen Break',
  'tapToStart': 'Tap to start',
  'start': 'Start',
  'pause': 'Pause',
  'reset': 'Reset',
  'selfCare': 'Self-Care Menu',
  'ideas': 'ideas',
  'journal': 'Journal',
  'writeFreely': 'Write freely',
  'journalHint': 'How did today feel?',
  'journalPlusHint': 'Journal Plus: try “What did my body need?”',
  'reminders': 'Reminders',
  'inAppOnly': 'On-device only',
  'remindersHint': 'Optional phone alerts at 8:00, 13:00, and 8:30 PM. On this device only — no tracking.',
  'reminderMorning': 'Morning hydrate',
  'reminderMidday': 'Midday move',
  'reminderEvening': '8:30 PM wind-down',
  'reminderMorningTime': '8:00 AM',
  'reminderMiddayTime': '1:00 PM',
  'reminderEveningTime': '8:30 PM',
  'reminderAllowAlerts': 'Allow phone alerts',
  'reminderPermissionDenied': 'Alerts are off in system settings.',
  'reminderMorningBody': 'A cup now. Log it on Today.',
  'reminderMiddayBody': 'A short move keeps the deck going.',
  'reminderEveningBody': 'Wind down and reflect. Observation only.',
  'streakStart': 'Log one thing to start a streak',
  'streakDays': '{n}-day streak',
  'streakHydrateLine': 'Hydration {n} days · Observation only',
  'streakMoveLine': 'Movement {n} days · Observation only',
  'journalPlusTitle': 'What did my body need?',
  'moodNoteHint': 'A word for today',
  'breath478plus': '4-7-8 · 4 min',
  'eveningReminder': 'Evening Reminder',
  'eveningHint': '8:30 PM · stays on this phone',
  'patternStudio': 'Pattern Studio',
  'days': 'days',
  'energy': 'Energy',
  'patternNote': 'Pattern',
  'streaks': 'Streaks',
  'experiments': 'Experiments',
  'experimentHint': 'Try one habit change and keep it on-device.',
  'weeklyReflection': 'Weekly Reflection',
  'wentWell': 'What went well?',
  'whatHard': 'What was hard?',
  'whatNext': 'What next?',
  'tapToWrite': 'Tap to write',
  'taskHint': 'Title',
  'save': 'Save',
  'cancel': 'Cancel',
  'skipOnboard': 'Skip',
  'next': 'Next',
  'getStarted': 'Get started',
  'onboardTitle1': 'Track, don’t diagnose',
  'onboardDesc1': 'Water, meals, movement, sleep, and mood — typed by you. Never from a watch.',
  'onboardTitle2': 'Build the day',
  'onboardDesc2': 'Workout checks, meal notes, habit stack, breathing, screen-break timer, optional phone reminders.',
  'onboardTitle3': 'Pattern Studio',
  'onboardDesc3': '7 or 30 days of insight. Observations only — not medical advice.',
  'dashboard': 'Today',

  'shopTagline': 'Looks, tools, and coin packs',
  'shopDailyHarvest': 'Daily coins',
  'shopNowGrowing': 'In use',
  'shopSeedRack': 'Themes',
  'shopPlotBeds': 'Backgrounds',
  'shopCardStyles': 'Card styles',
  'shopToolshed': 'Power-ups',
  'shopVipBadge': 'PRO',
  'shopCatalog': 'Shop',
  'shopMore': 'More',
  'shopPacks': 'Coin packs',
  'shopToday': 'Today',
  'shopMenuAll': 'All',
  'shopMenuPremium': 'Premium',
  'shopMenuThemes': 'Themes',
  'shopMenuBackgrounds': 'Backgrounds',
  'shopMenuSkins': 'Styles',
  'shopMenuFeatures': 'Features',
  'shopRemoveAds': 'Remove ads',
  'shopRemoveAdsDesc': 'Hide coin prompts around the deck.',
  'shopThemeDefault': 'Sage deck',
  'shopThemeDefaultDesc': 'Cream cards and navy bar',
  'shopBgDefault': 'Soft linen',
  'shopBgDefaultDesc': 'Warm off-white field',
  'shopSkinDefault': 'Soft card',
  'shopSkinDefaultDesc': 'Rounded paper cards',
  'shopThemeEmerald': 'Mint calm',
  'shopThemeEmeraldDesc': 'Green wellness wash',
  'shopThemeGold': 'Warm sand',
  'shopThemeGoldDesc': 'Amber evening cards',
  'shopThemeMidnight': 'Dusk navy',
  'shopThemeMidnightDesc': 'Quiet night mode',
  'shopBgForest': 'Garden haze',
  'shopBgForestDesc': 'Soft green behind cards',
  'shopBgAurora': 'Dawn mist',
  'shopBgAuroraDesc': 'Blue-lilac wash',
  'shopBgSunset': 'Blush dusk',
  'shopBgSunsetDesc': 'Warm pink traces',
  'shopSkinSoft': 'Pebble',
  'shopSkinSoftDesc': 'Extra-round cards',
  'shopSkinNeon': 'Ink edge',
  'shopSkinNeonDesc': 'Stronger card outline',
  'shopFeatDoubleCoins': 'Double coins',
  'shopFeatDoubleCoinsDesc': 'Earn 2× from daily claim, spin, and saves',
  'shopFeatHydrate': 'Hydrate Plus',
  'shopFeatHydrateDesc': 'Raise the water goal to 10 cups',
  'shopFeatMeal': 'Meal Plus',
  'shopFeatMealDesc': 'A fourth meal/snack slot',
  'shopFeatMove': 'Move Plus',
  'shopFeatMoveDesc': 'Raise movement goal to 60 min',
  'shopFeatBreath': 'Breath Plus',
  'shopFeatBreathDesc': '4-minute breathing sit',
  'shopFeatBreak': 'Break Plus',
  'shopFeatBreakDesc': '25-minute screen-break timer',
  'shopFeatCare': 'Care Plus',
  'shopFeatCareDesc': 'Extra self-care ideas',
  'shopFeatPattern': 'Pattern 90',
  'shopFeatPatternDesc': 'Unlock the 90-day Pattern Studio range',
  'shopFeatJournal': 'Journal Plus',
  'shopFeatJournalDesc': 'An extra reflection prompt on Build',

  'buy': 'Unlock',
  'owned': 'Owned',
  'equipped': 'Active',
  'equip': 'Use',
  'resetDefault': 'Use default look',
  'resetDefaultDesc': 'Sage theme, linen field, soft cards',
  'lookResetDone': 'Default look restored',
  'currentLook': 'Look',
  'purchaseSuccess': 'Unlocked in WellnessDeck',
  'purchaseFailed': 'Purchase failed. Try again.',
  'coinsAdded': 'Coins added',
  'coinsAddedWithBonus': 'Coins added — bonus included',
  'removeAdsUnlocked': 'Ads removed',
  'dailyReward': 'Daily reward',
  'dailyClaimed': 'Claimed',
  'claimDaily': 'Claim',
  'loginStreak': '{days}-day streak',
  'spinWheel': 'Lucky spin',
  'spinNow': 'Spin',
  'spinUsed': 'Come back tomorrow',
  'earnCoins': 'Daily coins',
  'earnCoinsDesc': 'Claim the day, spin, or buy a pack',
  'buyCoins': 'Buy coin packs',
  'buyCoinsDesc': 'Instant coins via Google Play',
  'promoBuyShort': 'Buy',
  'levelRewardEarned': 'Deck reward',
  'dailyRewardClaimed': 'Daily reward claimed',
  'spinRewardEarned': 'Spin reward earned',
  'promoTitle': 'Need more coins?',
  'promoSubtitle': 'Packs unlock looks and extras',
  'promoBuy': 'Buy coins',
  'restorePurchases': 'Restore purchases',
  'billingUnavailable': 'Billing unavailable',
  'billingDisabled': 'Play purchases are off. Shop coins still work.',
  'networkError': 'Network error. Check your connection.',
  'timeoutError': 'Request timed out. Try again.',
  'configOffline': 'Using offline config',
  'privacyPolicy': 'Privacy Policy',
  'privacyPolicyTitle': 'Privacy Policy',
  'privacyPolicyBody':
      'WellnessDeck stores hydration, meals, movement, sleep you type, mood, journal, look, and coins on this device. Optional local reminders stay on the phone and only run if you allow alerts. We do not connect to HealthKit, wearables, a microphone, or location. We do not diagnose. Coin packs and Remove ads go through Google Play. A remote config only checks whether Play billing should stay on.',
  'darkMode': 'Dark mode',
  'about': 'About',
  'version': 'Version {v}',
  'appearance': 'Appearance',
  'jobsThisWeek': '{n} cups logged today',
  'applied': 'Applied',
  'insufficientCoins': 'Not enough coins',
  'insufficientCoinsDetail': 'You need {count} more coins for this item.',
  'getMorePoints': 'Get coins',
  'alreadyOwned': 'Already owned',
  'openingBilling': 'Opening Google Play…',
  'buyViaPlay': 'Buy via Play',
  'active': 'Active',
  'useDefault': 'Default',
  'apply': 'Apply',
  'unlocked': 'Unlocked',
  'configTimeout': 'Connection timed out',
  'configNetworkError': 'Network error',
  'productsNotFound': 'Products not configured yet',
  'earnCoinsHint': 'Or earn free coins from the daily claim',
  'coinBalanceLabel': 'Your balance',
  'firstPurchaseBonus': '+50% first purchase bonus',
  'firstPurchaseBadge': '+50% bonus',
  'purchasePromoDesc': 'Get {coins} coins — enough for premium items.',
  'hotDealBadge': 'HOT',
  'bestValueBadge': 'BEST',
  'coinBonusExtra': '{base} + {bonus} bonus',
  'coinPack': 'Pack {num}',
  'promoCompactTitle': 'Need coins?',
  'promoHotDealDesc': 'Pack {pack} is {percent}% extra this week.',
  'promoHotDeal': 'Weekly deal',
  'promoBuyNow': 'Buy now',
  'promoUnlockRemaining': '{count} coins to next unlock',
  'promoUnlockReady': 'Ready to unlock in Shop',
  'coinEarned': '+{amount} coins',
  'coinRewardSub': 'Balance: {balance}',
};
